name: CI
on:
  push:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        jobtype: [ 4 ]
        compile-java: [ 11, 17 ]
        runtime-java:
          - 8   # baseline
          - 9   # Jigsaw / module JAXB and javax.annotation bundled
          - 11  # LTS / modules no longer bundled
          - 17  # LTS
        include:
          - { jobtype: 1, compile-java: 11 }
          - { jobtype: 1, compile-java: 17 }
          - { jobtype: 2, compile-java: 11 }
          - { jobtype: 2, compile-java: 17 }
          - { jobtype: 3, compile-java: 11 }
          - { jobtype: 3, compile-java: 17 }
          - { jobtype: 5, compile-java: 11 }
          - { jobtype: 5, compile-java: 17 }
    env:
      JAVA_OPTS: -Xmx3G -Xss6M -Dfile.encoding=utf8
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: "zulu@1.${{ matrix.compile-java }}"
      - uses: coursier/cache-action@v6

      - name: Install runtime Java
        if: ${{ matrix.jobtype == 4 }}
        env:
          RUNTIME_JAVA: "zulu@1.${{ matrix.runtime-java }}"
        run: |
          RUNTIME_JAVA="$(jabba ls-remote | grep "${RUNTIME_JAVA}." | head -n 1)"
          echo "Installing ${RUNTIME_JAVA}"
          jabba install "${RUNTIME_JAVA}"
          echo "RUNTIME_JAVA_HOME=$(jabba which --home "${RUNTIME_JAVA}")" >> $GITHUB_ENV

      - name: Build and test
        run: |
          case ${{ matrix.jobtype }} in
            1)
              sbt -v test docs/mdoc scalafmtCheckAll scalafmtSbtCheck headerCheckAll
              ;;
            2)
              sbt -v "core/scripted jooq/*" "checker/scripted jooq-checker/*"
              ;;
            3)
              sbt -v "codegen/scripted jooq-codegen/features"
              ;;
            4)
              sbt -v "codegen/scripted jooq-codegen/jooq-versions"
              ;;
            5)
              sbt -v "codegen/scripted it-flyway-sbt/*"
              ;;
            *)
              echo "unknown jobtype"
              exit 1
          esac

      - name: Cleanup
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/.sbt             -name "*.lock"                -delete || true
          find $HOME/.ivy2/cache      -name "ivydata-*.properties"  -delete || true
          find $HOME/.cache/coursier  -name "ivydata-*.properties"  -delete || true
