name: CI
on:
  push:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        task: [ core, checker, codegen, compat, flyway ]
        scripted-java:
          - 8   # baseline
          - 9   # Jigsaw / JAXB and javax.annotation bundled
          - 11  # LTS / JAXB and javax.annotation no longer bundled
          - 17  # LTS
          - 21  # LTS
        scripted-scala:
          - 3.3.3
          - 2.13.14
        include:
          - task: test
          - { task: checker, scripted-java: 17, scripted-scala: 2.12.19 }
          - { task: checker, scripted-java: 21, scripted-scala: 2.12.19 }
        exclude:
          - { task: core, scripted-java: 8 }
          - { task: core, scripted-java: 9 }
          - { task: core, scripted-java: 11 }
          - { task: checker, scripted-java: 8 }
          - { task: checker, scripted-java: 9 }
          - { task: checker, scripted-java: 11 }
          - { task: codegen, scripted-java: 8 }
          - { task: codegen, scripted-java: 9 }
          - { task: codegen, scripted-java: 11 }
          - { task: flyway, scripted-java: 8 }
          - { task: flyway, scripted-java: 9 }
          - { task: flyway, scripted-java: 11 }
    env:
      JAVA_OPTS: -Xmx3G -Xss6M -Dfile.encoding=utf8
    steps:
      - uses: actions/checkout@v4

      - id: scripted_java
        if: ${{ matrix['scripted-java'] != null }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.scripted-java }}

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: sbt

      - name: Build and test
        if: ${{ matrix.task == 'test' }}
        run: |
          sbt -v +test docs/mdoc +scalafmtCheckAll scalafmtSbtCheck +headerCheckAll versionPolicyCheck

      - name: Build and scripted
        if: ${{ matrix.task != 'test' }}
        env:
          CI_TASK: ${{ matrix.task }}
          SCRIPTED_SCALA: ${{ matrix.scripted-scala }}
          SCRIPTED_JAVA_HOME: ${{ steps.scripted_java.outputs.path }}
        run: |
          case "$CI_TASK" in
            core)
              sbt -v "core/scripted jooq/*"
              ;;
            checker)
              sbt -v "++${SCRIPTED_SCALA}" "checker/scripted jooq-checker/*"
              ;;
            codegen)
              sbt -v "codegen/scripted jooq-codegen/*"
              ;;
            compat)
              sbt -v "codegen/scripted jooq-versions/*"
              ;;
            flyway)
              sbt -v "codegen/scripted it-flyway-sbt/*"
              ;;
            *)
              echo "unknown task"
              exit 1
          esac
