name: CI
on:
  push:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        task: [ compat ]
        compile-java: [ 11, 17 ]
        runtime-java:
          - 8   # baseline
          - 9   # Jigsaw / module JAXB and javax.annotation bundled
          - 11  # LTS / modules no longer bundled
          - 17  # LTS
        include:
          - { task: codegen, compile-java: 11 }
          - { task: codegen, compile-java: 17 }
          - { task: checker, compile-java: 11 }
          - { task: checker, compile-java: 17 }
          - { task: mdoc, compile-java: 11 }

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        id: runtimejava
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.runtime-java }}
          check-latest: true
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.compile-java }}
          check-latest: true
      - name: Setup SBT
        run: |
          curl -sL https://raw.githubusercontent.com/sbt/sbt/develop/sbt > /usr/local/bin/sbt
          chmod +x /usr/local/bin/sbt
      - uses: coursier/cache-action@v6

      - run: cp ./.github/workflows/.jvmopts .

      - name: Disable incompatible tests
        if: ${{ matrix.task == 'compat' && matrix.runtime-java < 11 }}
        run: |
          sbt -v "codegen/disableIncompatibleTestsWithEarlierThanJava11"

      - name: Build and test
        env:
          RUNTIME_JAVA_HOME: ${{ steps.runtimejava.outputs.path }}
        run: |
          case ${{ matrix.task }} in
            codegen)
              sbt -v "codegen/scripted jooq-codegen/*"
              ;;
            compat)
              sbt -v "codegen/scripted jooq-codegen-compat/*"
              ;;
            checker)
              sbt -v "checker/scripted jooq-checker/*"
              ;;
            mdoc)
              sbt -v "docs/mdoc"
              ;;
            *)
              echo "unknown task"
              exit 1
          esac

      - name: Delete non-cached files
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/.sbt             -name "*.lock"                -delete || true
          find $HOME/.ivy2/cache      -name "ivydata-*.properties"  -delete || true
          find $HOME/.cache/coursier  -name "ivydata-*.properties"  -delete || true
