name: CI
on:
  push:
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        jobtype: [ 2, 3, 4, 5 ]
        java: [ 17 ]
        scripted-java:
          - 8   # baseline
          - 9   # Jigsaw / module JAXB and javax.annotation bundled
          - 11  # LTS / modules no longer bundled
          - 17  # LTS
        include:
          - { jobtype: 1, java: 17 }
        exclude:
          - { jobtype: 2, scripted-java: 8 }
          - { jobtype: 2, scripted-java: 9 }
          - { jobtype: 3, scripted-java: 8 }
          - { jobtype: 3, scripted-java: 9 }
          - { jobtype: 5, scripted-java: 8 }
          - { jobtype: 5, scripted-java: 9 }
    env:
      JAVA_OPTS: -Xmx3G -Xss6M -Dfile.encoding=utf8
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: "zulu@1.${{ matrix.java }}"
      - uses: coursier/cache-action@v6

      - name: Install Java for scripted
        if: ${{ matrix.jobtype >= 2 }}
        env:
          SCRIPTED_JAVA: "zulu@1.${{ matrix.scripted-java }}"
        run: |
          SCRIPTED_JAVA="$(jabba ls-remote | grep "${SCRIPTED_JAVA}\." | head -n 1)"
          echo "Installing ${SCRIPTED_JAVA}"
          jabba install "${SCRIPTED_JAVA}"
          echo "SCRIPTED_JAVA_HOME=$(jabba which --home "${SCRIPTED_JAVA}")" >> $GITHUB_ENV

      - name: Build and test
        run: |
          case ${{ matrix.jobtype }} in
            1)
              sbt -v test docs/mdoc scalafmtCheckAll scalafmtSbtCheck headerCheckAll
              ;;
            2)
              sbt -v "core/scripted jooq/*" "checker/scripted jooq-checker/*"
              ;;
            3)
              sbt -v "codegen/scripted jooq-codegen/*"
              ;;
            4)
              sbt -v "codegen/scripted jooq-versions/*"
              ;;
            5)
              sbt -v "codegen/scripted it-flyway-sbt/*"
              ;;
            *)
              echo "unknown jobtype"
              exit 1
          esac

      - name: Cleanup
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/.sbt             -name "*.lock"                -delete || true
          find $HOME/.ivy2/cache      -name "ivydata-*.properties"  -delete || true
          find $HOME/.cache/coursier  -name "ivydata-*.properties"  -delete || true
